steps:
  # Build the image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/photogallery:$COMMIT_SHA', '.']

  # Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/photogallery:$COMMIT_SHA']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/google-cloud-cli'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'photogallery'
      - '--image'
      - 'gcr.io/$PROJECT_ID/photogallery:$COMMIT_SHA'
      - '--region'
      - 'me-central1'
      - '--platform'
      - 'managed'
      - '--quiet'

images:
  - 'gcr.io/$PROJECT_ID/photogallery:$COMMIT_SHA'
